### PR TITLE
Check to not go over the line count, fixes issue #6.

### PR DESCRIPTION
**Pull request by krzysztof-pawlik-gat**

### CODE REVIEW

**Comment by krzysztof-pawlik-gat** [comment]
@vbanthia could you review this pr?

**Comment by vbanthia** [comment]
@krzysztof-pawlik-gat  

Sorry, I did not notice this. I will test it tomorrow and merge it.

**Comment by krzysztof-pawlik-gat** [comment]
Thank you!

**Comment by vbanthia** [comment]
@krzysztof-pawlik-gat 

Thank you for your pull request and detailed issue. I had to tweak your pull request a bit because it wasn't solving issue properly. I merged changes here, https://github.com/vbanthia/rspec_html_reporter/commit/7d83b67979feb595ff74911f0bb8593aa7a794f9

I have release `1.0.1`. Please check this version and let me know if there is any issue.

**Pull request closed without merging**
